export const MUSIC_LIBRARY_SETTER = 'MUSIC_LIBRARY_SETTER';
export const USER_SETTER = 'USER_SETTER';
export const LOGIN = 'LOGIN';
export const REQEST_BANNER = 'REQEST_BANNER';
export const CURRENT_TIME = 'CURRENT_TIME';
export const CURRENT_TIME_SETTER = 'CURRENT_TIME_SETTER';
